# Generated by Django 3.0.7 on 2020-10-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0036_auto_20201002_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
