# Generated by Django 3.0.7 on 2020-10-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20201002_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
