# Generated by Django 3.0.7 on 2020-10-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
