# Generated by Django 3.0.7 on 2020-10-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20201007_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=models.CharField(max_length=12, verbose_name='телефон'),
        ),
    ]
